[project]
name = "zapbench"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "3.11"
pip = "*"
matplotlib = ">=3.10.6,<4"
scienceplots = ">=2.1.1,<3"
python-dotenv = ">=1.1.1,<2"

[pypi-dependencies]
zapbench = { path = ".", editable = true }
jax = { version = ">=0.7.0,<0.8", extras = ["cuda12"] }

[feature.dev.pypi-dependencies]
pytest = "*"
pytest-xdist = "*"
pylint = ">=2.6.0"
pyink = "*"
